apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: flask-app
spec:
  containers:
  - image: thulasiprasad2000/task2-app
    name: flask-app
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: p@ssw0rd
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP