apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-app
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: flask-app
  name: flask-app
spec:
  containers:
  - image: thulasiprasad2000/task2-app:latest
    name: flask-app
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: Password123
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  containers:
  - image: thulasiprasad2000/task2-db:latest
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: Password123
    ports:
    - containerPort: 3306