apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replicas
  labels:
    task: task2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - image: thulasiprasad2000/task2-app
        name: flask-app
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-root-password
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  type: ClusterIP
  selector:
    app: flask-app
  ports:
  - port: 5000
    protocol: TCP