apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: db
spec:
  containers:
  - image: thulasiprasad2000/task2-db
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: p@ssw0rd
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - port: 3306
    protocol: TCP